{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "journey-hub.fullname" . }}
  labels:
    {{- include "journey-hub.labels" . | nindent 4 }}
spec:
  {{- with .Values.route.host }}
  host: {{ . | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "journey-hub.fullname" . }}
  port:
    targetPort: http
  tls:
    termination: {{ .Values.route.tlsTermination }}
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
